spring.application.name=gestion

server.port=8000

spring.datasource.url=jdbc:mysql://localhost:3306/bencol_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

app.jwt.secret=runicsoft-bencol-secret-key-development-2026-super-segura-cambiar-en-produccion
app.jwt.expiration-minutes=1440